name: test
on: 
    workflow_dispatch:
permissions:
    pull-requests: write
jobs:
  Build_development:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: Marius0101/create-pull-request@v1
        with:
            token: ${{ secrets.TOKEN }}
            title: 'Add new feature' 
            head: 'feature/add-invoke-github-action-function' 
            base: 'develop' 
